CREATE DATABASE DEMOADR;
GO

USE DEMOADR
GO

SET STATISTICS TIME ON

BEGIN TRANSACTION
DROP TABLE IF EXISTS t1;

SELECT TOP 5000000 t1.* 
INTO t1 
FROM sys.all_objects AS t1
CROSS JOIN sys.all_objects AS t2
CROSS JOIN sys.all_objects AS t3

ROLLBACK TRAN

-- activar adr

ALTER DATABASE DEMOADR
SET ACCELERATED_DATABASE_RECOVERY = ON;
GO

-- probamos de nuevo

BEGIN TRANSACTION
DROP TABLE IF EXISTS t1;

SELECT TOP 5000000 t1.* 
INTO t1 
FROM sys.all_objects AS t1
CROSS JOIN sys.all_objects AS t2
CROSS JOIN sys.all_objects AS t3

ROLLBACK TRAN


ALTER DATABASE [DEMOADR] ADD FILEGROUP [VersionStoreFG];
GO
ALTER DATABASE [DEMOADR] ADD FILE ( NAME = N'VersionStoreFG'
, FILENAME = N'f:\sql\VersionStore.ndf'
, SIZE = 8192KB , FILEGROWTH = 65536KB )
TO FILEGROUP [VersionStoreFG];
GO

ALTER DATABASE DEMOADR
SET ACCELERATED_DATABASE_RECOVERY = OFF;

ALTER DATABASE [demoadr] SET ACCELERATED_DATABASE_RECOVERY = ON
(PERSISTENT_VERSION_STORE_FILEGROUP = [VersionStoreFG]);

USE master 
DROP DATABASE DEMOADR