/*
BORRAR REGISTROS DUPLICADOS
*/

USE TEMPDB

DROP TABLE IF EXISTS DBO.EMPLEADOS  

CREATE TABLE DBO.EMPLEADOS 
(ID INT IDENTITY PRIMARY KEY,
 NOMBRE VARCHAR(255),
 APELLIDO VARCHAR(255)
)

INSERT INTO DBO.EMPLEADOS (NOMBRE,APELLIDO)
VALUES ('MAXI','ACCOTTO')
GO 4

INSERT INTO DBO.EMPLEADOS (NOMBRE,APELLIDO)
VALUES ('GASTON','LOPEZ')
GO 2

INSERT INTO DBO.EMPLEADOS (NOMBRE,APELLIDO)
VALUES ('LEONARDO','ACCOTTO')

SELECT * FROM DBO.EMPLEADOS 

-- BUSCAMOS DUPLICADOS
WITH C AS
(
 SELECT ID,NOMBRE,APELLIDO,
 ROW_NUMBER() OVER (PARTITION BY 
                   NOMBRE,APELLIDO
                   ORDER BY ID) AS DUPLICADO
 FROM DBO.EMPLEADOS 
)
SELECT * FROM C 
WHERE DUPLICADO > 1

-- BORRAMOS REGISTROS DUPLICADOS

WITH C AS
(
 SELECT ID,NOMBRE,APELLIDO,
 ROW_NUMBER() OVER (PARTITION BY 
                   NOMBRE,APELLIDO
                   ORDER BY ID) AS DUPLICADO
 FROM DBO.EMPLEADOS 
)
DELETE FROM C 
WHERE DUPLICADO > 1

-- VERIFICAMOS
SELECT * FROM DBO.EMPLEADOS 
