USE TEMPDB  
GO

CREATE OR ALTER PROC USP_DEMO_ERROR1
AS
 SET NOCOUNT ON
 SELECT 1/0 -- ERROR
 SELECT 100/1
GO

CREATE OR ALTER PROC USP_DEMO
AS
 SET NOCOUNT ON
 SELECT 1/1
GO


 EXEC USP_DEMO_ERROR1

DECLARE @I INT
EXECUTE @I = USP_DEMO_ERROR1

SELECT @I

EXECUTE @I = USP_DEMO

SELECT @I

-- CONTROL DE ERRORES SIMPLE PARTE 1

CREATE OR ALTER PROC USP_DEMO_ERROR1
AS
 SET NOCOUNT ON
BEGIN TRY

 SELECT 1/0 -- ERROR
 SELECT 100/1
END TRY

BEGIN CATCH
 THROW
END CATCH
GO

EXEC USP_DEMO_ERROR1

CREATE OR ALTER PROC USP_DEMO_ERROR1
AS
 SET NOCOUNT ON
BEGIN TRY

 SELECT 1/0 -- ERROR
 SELECT 100/1
END TRY

BEGIN CATCH
 THROW 51000,'Error general',1
END CATCH
GO

EXEC USP_DEMO_ERROR1

-- CON TRANSACCIONES
DROP TABLE IF EXISTS DBO.T1 
DROP TABLE IF EXISTS DBO.T2


CREATE TABLE DBO.T1 (ID INT IDENTITY PRIMARY KEY,
                     C1 VARCHAR(255) NOT NULL)
							 
CREATE TABLE DBO.T2 (ID INT IDENTITY PRIMARY KEY,
                     C1 VARCHAR(255) NULL)
GO

CREATE OR ALTER PROC DBO.USP_ERROR_TRANSAC
AS
BEGIN
 BEGIN TRY
   BEGIN TRAN
     INSERT INTO T2 (C1) VALUES ('Hola mundo')

	 INSERT INTO T1 (C1) VALUES (null)
   COMMIT TRAN 
 END TRY

 BEGIN CATCH
   THROW -- SIN CONTROL DE TRANSACCIONES (MAL)
 END CATCH

END

SELECT * FROM T1
SELECT * FROM T2

EXEC DBO.USP_ERROR_TRANSAC
SELECT * FROM T1
SELECT * FROM T2

TRUNCATE TABLE T1
TRUNCATE TABLE T2

-- CONTROL DE ERRORES CON TRANSACCIONES DE FORMA CORRECTA

CREATE OR ALTER PROC DBO.USP_ERROR_TRANSAC
AS
BEGIN
 BEGIN TRY
   BEGIN TRAN
     INSERT INTO T2 (C1) VALUES ('Hola mundo')

	 INSERT INTO T1 (C1) VALUES (null)
   COMMIT TRAN
 END TRY

 BEGIN CATCH
   IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
   THROW;
 END CATCH
END

SELECT * FROM T1
SELECT * FROM T2

EXEC DBO.USP_ERROR_TRANSAC
SELECT * FROM T1
SELECT * FROM T2
