USE STACKOVERFLOW2010 
GO

SELECT COUNT(*) FROM DBO.POSTS ;

-- THIS IS FAR MORE EFFICIENT, AND NO LESS ACCURATE:

SELECT SUM([ROWS]) FROM SYS.PARTITIONS 
  WHERE [OBJECT_ID] = OBJECT_ID(N'DBO.POSTS')
  AND INDEX_ID IN (0,1);

-- TODAS LAS TABLAS

SELECT SCHEMA_NAME(T.SCHEMA_ID) AS ESQUEMA,  
T.NAME  AS TABLA, 
SUM([ROWS]) AS CANTIDAD_ROWS
,
P.DATA_COMPRESSION_DESC
FROM SYS.PARTITIONS P
INNER JOIN SYS.TABLES T
ON P.OBJECT_ID = T.OBJECT_ID 
  WHERE  INDEX_ID IN (0,1)
GROUP BY T.SCHEMA_ID,T.NAME, P.DATA_COMPRESSION_DESC
ORDER BY 3 DESC

-- SELECT * FROM SYS.PARTITIONS 
